# Generated by Django 4.2.7 on 2023-11-16 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eticket', '0003_alter_event_host_alter_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eticket.venue'),
        ),
    ]
