# Generated by Django 4.2.7 on 2023-11-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eticket', '0005_event_ticketprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticketQuantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
