# Generated by Django 4.2.7 on 2023-12-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eticket', '0007_remove_ticket_price_ticket_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='row',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seatNum',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
